// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ebrijjavqdjndquzerqf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVicmlqamF2cWRqbmRxdXplcnFmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5MTg5ODEsImV4cCI6MjA2MjQ5NDk4MX0.AJDr5ZufMsxLm72_GGShaQMoWZ8nYUlvANbNWQcnOeA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);